# Generated by Django 4.1 on 2022-12-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_stusent_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stusent_Feedback',
            new_name='Student_Feedback',
        ),
    ]
